FROM ubuntu:jammy

# Install dependencies in a single layer
RUN apt-get update && \
    apt-get install -yq \
    sudo \
    apt-utils \
    vim \
    curl \
    gpg \
    unzip \
    wget \
    libcap2-bin \
    ufw \
    lsb-release && \
    apt-get clean all