FROM ansible-jdk:latest

RUN curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key |  \
    sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null && \
    echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ |  \
    sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null && \
    apt-get update &&  \
    apt-get install jenkins -y
EXPOSE 8080
ENTRYPOINT ["sh", "-c", "jenkins;tail -f /dev/null"]