FROM ubuntu:jammy
# Set environment variable to prevent prompts
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -yq \
    sudo \
    apt-utils \
    vim \
    curl \
    git \
    gpg \
    unzip \
    wget \
    libcap2-bin \
    ufw \
    software-properties-common \
    openjdk-17-jdk \
    maven \
    lsb-release && \
    apt-get clean all &&  \
    add-apt-repository --yes --update ppa:ansible/ansible && \
    apt install ansible -yq && \
    echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> /etc/environment && \
    echo "MAVEN_HOME=/usr/share/maven" >> /etc/environment && \
    curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key |  \
    sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null && \
    echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ |  \
    sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null && \
    apt-get update &&  \
    apt-get install jenkins -y
EXPOSE 8080
ENTRYPOINT ["sh", "-c", "jenkins;tail -f /dev/null"]